export default {
    NEW_MESSAGE: 'NEW MESSAGE',
    UPDATE_MESSAGES_FOR_ROOM: 'UPDATE MESSAGES FOR ROOM',
    GET_ALL_MESSAGES_FOR_ROOM_REQUEST: 'GET ALL MESSAGES FOR ROOM REQUEST',
    GET_ALL_MESSAGES_FOR_ROOM_RESPONSE: 'GET ALL MESSAGES FOR ROOM RESPONSE'
}