export default {
    GET_ALL_USERS_FOR_ROOM_REQUEST: 'GET ALL USERS FOR ROOM REQUEST',
    GET_ALL_USERS_FOR_ROOM_RESPONSE: 'GET ALL USERS FOR ROOM RESPONSE',
    AUTHORIZE_USER_REQUEST: 'AUTHORIZE USER REQUEST',
    AUTHORIZE_USER_SUCCESS_RESPONSE: 'AUTHORIZE USER SUCCESS RESPONSE',
    AUTHORIZE_USER_FAIL_RESPONSE: 'AUTHORIZE USER FAIL RESPONSE'
}