export default {
  GET_ALL_USERS_FOR_ROOM_REQUEST: 'GET ALL USERS FOR ROOM REQUEST',
  GET_ALL_USERS_FOR_ROOM_RESPONSE: 'GET ALL USERS FOR ROOM RESPONSE',
  AUTHENTICATE_USER_REQUEST: 'AUTHENTICATE USER REQUEST',
  AUTHENTICATE_USER_SUCCESS_RESPONSE: 'AUTHENTICATE USER SUCCESS RESPONSE',
  AUTHENTICATE_USER_FAIL_RESPONSE: 'AUTHENTICATE USER FAIL RESPONSE'
};
